
services:
  redis:
    image: redis:alpine
    restart: always

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - PROMETHEUS_PORT=5000 

  worker:
    build: .
    command: ["python", "worker.py"]
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always

  locust:
    image: locustio/locust
    volumes:
      - ./locustfile.py:/locustfile.py  
    ports:
      - "8089:8089"  
    command: -f /locustfile.py --host=http://web:5000 
