global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['web:5000']  

  - job_name: 'worker'
    static_configs:
      - targets: ['worker:5000']  
